"""Generate src/mad_tables.h from nfs3.exe (read-only).

Every number in the header is read from the executable at the address given
next to it, so the decompiled decoder uses exactly the data the game uses.
"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(__file__))
from disx import read  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'mad_tables.h')


def i32s(addr, n):
    return list(struct.unpack('<%di' % n, read(addr, 4 * n)))


def f32(addr):
    return struct.unpack('<f', read(addr, 4))[0]


def arr(name, ctype, values, per_line=8, fmt='%d'):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append('    ' + ', '.join(fmt % v for v in values[i:i + per_line]) + ',')
    return 'static const %s %s[%d] = {\n%s\n};\n' % (ctype, name, len(values), '\n'.join(lines))


def recs(addr, n):
    v = i32s(addr, 4 * n)
    return [v[4 * k:4 * k + 4] for k in range(n)]


def main():
    out = []
    out.append('/* Generated by tools/extract_tables.py from nfs3.exe -- do not edit. */')
    out.append('#ifndef MAD_TABLES_H\n#define MAD_TABLES_H\n\n#include <stdint.h>\n')
    out.append('/* 0x5660c4: quantiser matrix, raster order (MPEG-1 default intra matrix). */')
    out.append(arr('MAD_QUANT_MATRIX', 'int32_t', i32s(0x5660c4, 64)))
    out.append('/* 0x56d02c: AAN IDCT prescale, Q13 (8192 = 1.0), raster order. */')
    out.append(arr('MAD_AAN_SCALE', 'int32_t', i32s(0x56d02c, 64)))
    zz = i32s(0x5688cc, 128)
    out.append('/* 0x5688cc: scan order as BYTE offsets into the 64-dword coefficient block.\n'
               ' * Only the first 64 belong to the scan; the rest is whatever follows in the\n'
               ' * executable, kept so an index past 63 reads what the original reads. */')
    out.append(arr('MAD_SCAN_OFFSET', 'int32_t', zz))
    out.append('/* 0x5652d4: AC code table A, 95 records {length, run<<10|level(10-bit),\n'
               ' * unused, code left-aligned in 16 bits}.  Record 0 is end-of-block and is\n'
               ' * not used by the table builder (it starts at record 1). */')
    ra = recs(0x5652d4, 95)
    out.append('static const int32_t MAD_VLC_A[95][4] = {\n' +
               '\n'.join('    {%d, %d, %d, 0x%04x},' % (r[0], r[1], r[2], r[3] & 0xffffffff) for r in ra) + '\n};\n')
    rb = recs(0x5658c4, 128)
    out.append('/* 0x5658c4: AC code table B, 128 records, same layout; codes that start\n'
               ' * with eight zero bits, the length and code given without those eight. */')
    out.append('static const int32_t MAD_VLC_B[128][4] = {\n' +
               '\n'.join('    {%d, %d, %d, 0x%04x},' % (r[0], r[1], r[2], r[3] & 0xffffffff) for r in rb) + '\n};\n')
    k = i32s(0x56cdf8, 1)[0]
    out.append('/* 0x56cdf8..0x56ce08: IDCT constants. */')
    out.append('#define MAD_IDCT_K 0x%08xu /* %.10f in Q31 (sqrt(1/2)) */' % (k & 0xffffffff, k / 2.0 ** 31))
    out.append('static const uint32_t MAD_IDCT_C1_BITS = 0x%s; /* 0x56cdfc  %.9g */' % (read(0x56cdfc, 4)[::-1].hex(), f32(0x56cdfc)))
    out.append('static const uint32_t MAD_IDCT_C0_BITS = 0x%s; /* 0x56ce00  %.9g */' % (read(0x56ce00, 4)[::-1].hex(), f32(0x56ce00)))
    out.append('static const uint32_t MAD_IDCT_C2_BITS = 0x%s; /* 0x56ce04  %.9g */' % (read(0x56ce04, 4)[::-1].hex(), f32(0x56ce04)))
    out.append('static const uint32_t MAD_IDCT_MAGIC_BITS = 0x%s; /* 0x56ce08  %.1f = 1.5*2^52 */' % (read(0x56ce08, 4)[::-1].hex(), f32(0x56ce08)))
    out.append('\n#endif')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('\n'.join(out) + '\n')
    print('wrote', os.path.normpath(OUT))
    print('table B:')
    for i, r in enumerate(rb):
        print(i, r[0], 'run', (r[1] >> 10) & 0x3f, 'lvl', r[1] & 0x3ff, hex(r[3] & 0xffff))


if __name__ == '__main__':
    main()
